CREATE TABLE tbfichatecnicaitem (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id integer NOT NULL REFERENCES tbproduto (id),
    insumo_id integer NOT NULL REFERENCES tbproduto (id),
    quantidade numeric(19, 3) NOT NULL
);

CREATE INDEX idx_fichatecnicaitem_produto_id ON tbfichatecnicaitem (produto_id);
