CREATE TABLE tbpedidocompra (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id integer NOT NULL REFERENCES tbfornecedor (id),
    itens character varying(255) NOT NULL,
    valor_total numeric(19, 2) NOT NULL,
    status character varying(20) NOT NULL,
    dt_criacao timestamp(6) without time zone,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE INDEX idx_pedidocompra_empresa_id ON tbpedidocompra (empresa_id);
