CREATE TABLE tbentregador (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    telefone character varying(20),
    fl_ativo boolean,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE TABLE tbentrega (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente character varying(255) NOT NULL,
    endereco character varying(255) NOT NULL,
    entregador_id integer REFERENCES tbentregador (id),
    status character varying(30) NOT NULL,
    dt_criacao timestamp(6) without time zone,
    dt_saida timestamp(6) without time zone,
    dt_entrega timestamp(6) without time zone,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE INDEX idx_entregador_empresa_id ON tbentregador (empresa_id);
CREATE INDEX idx_entrega_empresa_id ON tbentrega (empresa_id);
