CREATE TABLE tbnotificacao (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icone character varying(50),
    cor character varying(20),
    titulo character varying(255),
    descricao character varying(500),
    lida boolean NOT NULL DEFAULT false,
    dt_criacao timestamp(6) without time zone,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE INDEX idx_notificacao_empresa_id ON tbnotificacao (empresa_id);
