CREATE TABLE tbintegracaoconfig (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave character varying(50) NOT NULL,
    credenciais_json text,
    ativo boolean NOT NULL DEFAULT false,
    empresa_id integer NOT NULL REFERENCES tbempresa (id)
);

CREATE UNIQUE INDEX idx_integracaoconfig_empresa_chave ON tbintegracaoconfig (empresa_id, chave);
