--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tbadicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbadicional (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    preco double precision NOT NULL,
    produto_id integer NOT NULL
);


--
-- Name: tbadicional_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbadicional ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbadicional_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcaixa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcaixa (
    id integer NOT NULL,
    diferenca double precision,
    dt_abertura timestamp(6) without time zone,
    dt_fechamento timestamp(6) without time zone,
    observacoes_abertura character varying(255),
    observacoes_fechamento character varying(255),
    status character varying(255),
    valor_apurado_informado double precision,
    valor_apurado_sistema double precision,
    valor_inicial double precision NOT NULL,
    empresa_id integer,
    usuario_abertura_id integer,
    usuario_fechamento_id integer
);


--
-- Name: tbcaixa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcaixa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcaixa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcardapio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcardapio (
    id integer NOT NULL,
    descricao character varying(255),
    dt_alteracao timestamp(6) without time zone,
    fl_ativo boolean,
    nome character varying(255) NOT NULL,
    padrao boolean,
    empresa_id integer
);


--
-- Name: tbcardapio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcardapio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcardapio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcashback_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcashback_config (
    id integer NOT NULL,
    fl_ativo boolean,
    percentual_acumulo double precision NOT NULL,
    valor_minimo_para_acumular double precision,
    empresa_id integer
);


--
-- Name: tbcashback_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcashback_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcashback_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcategoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcategoria (
    id integer NOT NULL,
    descricao character varying(255),
    dt_alteracao character varying(255),
    flativo boolean,
    nome character varying(255) NOT NULL,
    empresa_id integer
);


--
-- Name: tbcategoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcategoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcategoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcliente (
    id integer NOT NULL,
    dt_alteracao character varying(255),
    dt_criacao character varying(255),
    email character varying(255) NOT NULL,
    endereco character varying(255),
    nome character varying(255) NOT NULL,
    saldo_cashback double precision,
    telefone character varying(255) NOT NULL,
    empresa_id integer
);


--
-- Name: tbcliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcomanda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcomanda (
    id integer NOT NULL,
    dt_abertura timestamp(6) without time zone,
    dt_fechamento timestamp(6) without time zone,
    nome_cliente character varying(255),
    numero integer NOT NULL,
    status character varying(255),
    valor_total double precision,
    empresa_id integer,
    mesa_id integer NOT NULL,
    usuario_abertura_id integer
);


--
-- Name: tbcomanda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcomanda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcomanda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcomposicaoitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcomposicaoitem (
    id integer NOT NULL,
    nome character varying(255) NOT NULL,
    removivel boolean,
    produto_id integer NOT NULL
);


--
-- Name: tbcomposicaoitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcomposicaoitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcomposicaoitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbcupom; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbcupom (
    id integer NOT NULL,
    codigo character varying(255) NOT NULL,
    dt_validade_fim timestamp(6) without time zone,
    dt_validade_inicio timestamp(6) without time zone,
    fl_ativo boolean,
    limite_uso_por_cliente integer,
    limite_uso_total integer,
    tipo_desconto character varying(255) NOT NULL,
    valor_desconto double precision NOT NULL,
    valor_minimo_pedido double precision,
    empresa_id integer
);


--
-- Name: tbcupom_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbcupom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbcupom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbempresa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbempresa (
    id integer NOT NULL,
    cnpj character varying(255) NOT NULL,
    dt_alteracao timestamp(6) without time zone,
    dt_criacao timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    fl_ativo boolean,
    nome character varying(255) NOT NULL,
    slug character varying(255),
    stripe_account_id character varying(255),
    stripe_charges_enabled boolean,
    stripe_onboarding_status character varying(255),
    stripe_payouts_enabled boolean,
    telefone character varying(255),
    segmento_id integer
);


--
-- Name: tbempresa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbempresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbempresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbendereco; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbendereco (
    id integer NOT NULL,
    bairro character varying(255) NOT NULL,
    cep character varying(255) NOT NULL,
    cidade character varying(255) NOT NULL,
    complemento character varying(255),
    dt_alteracao character varying(255),
    numero integer NOT NULL,
    rua character varying(255) NOT NULL,
    cliente_id integer NOT NULL
);


--
-- Name: tbendereco_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbendereco ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbendereco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbestoque; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbestoque (
    id integer NOT NULL,
    dt_ultima_movimentacao timestamp(6) without time zone,
    estoque_minimo integer NOT NULL,
    quantidade_atual integer NOT NULL,
    produto_id integer NOT NULL
);


--
-- Name: tbestoque_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbestoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbestoque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbfornecedor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbfornecedor (
    id integer NOT NULL,
    cnpj character varying(255) NOT NULL,
    dt_criacao timestamp(6) without time zone,
    email character varying(255),
    fl_ativo boolean,
    nome character varying(255) NOT NULL,
    telefone character varying(255),
    empresa_id integer
);


--
-- Name: tbfornecedor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbfornecedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbfornecedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbitemcardapio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbitemcardapio (
    id integer NOT NULL,
    descricao_override character varying(255),
    disponivel boolean,
    foto_url character varying(255),
    ordem integer,
    preco_override double precision,
    cardapio_id integer NOT NULL,
    produto_id integer NOT NULL
);


--
-- Name: tbitemcardapio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbitemcardapio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbitemcardapio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbitemvenda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbitemvenda (
    id integer NOT NULL,
    custo_unitario double precision,
    desconto double precision,
    dt_alteracao character varying(255),
    observacao character varying(255),
    preco_unitario double precision NOT NULL,
    quantidade double precision NOT NULL,
    valor_total double precision,
    produto_id integer NOT NULL,
    venda_id integer NOT NULL
);


--
-- Name: tbitemvenda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbitemvenda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbitemvenda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbitemvendaadicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbitemvendaadicional (
    id integer NOT NULL,
    nome character varying(255),
    preco double precision,
    quantidade integer NOT NULL,
    adicional_id integer NOT NULL,
    item_venda_id integer NOT NULL
);


--
-- Name: tbitemvendaadicional_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbitemvendaadicional ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbitemvendaadicional_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbitemvendacomposicaoremovida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbitemvendacomposicaoremovida (
    id integer NOT NULL,
    composicao_item_id integer NOT NULL,
    item_venda_id integer NOT NULL
);


--
-- Name: tbitemvendacomposicaoremovida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbitemvendacomposicaoremovida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbitemvendacomposicaoremovida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbmesa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbmesa (
    id integer NOT NULL,
    dt_alteracao character varying(255),
    numero integer NOT NULL,
    status character varying(255) NOT NULL,
    empresa_id integer
);


--
-- Name: tbmesa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbmesa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbmesa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbmovimentacao_financeira; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbmovimentacao_financeira (
    id integer NOT NULL,
    categoria character varying(255) NOT NULL,
    descricao character varying(255),
    dt_alteracao character varying(255),
    tipo character varying(255) NOT NULL,
    valor double precision NOT NULL,
    caixa_id integer,
    empresa_id integer
);


--
-- Name: tbmovimentacao_financeira_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbmovimentacao_financeira ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbmovimentacao_financeira_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbpagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbpagamento (
    id integer NOT NULL,
    dt_alteracao character varying(255),
    dt_pagamento character varying(255),
    metodo character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    valor double precision NOT NULL,
    caixa_id integer,
    comanda_id integer,
    venda_id integer
);


--
-- Name: tbpagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbpagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbpagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbpedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbpedido (
    id integer NOT NULL,
    data_criacao timestamp(6) without time zone,
    nome_produto character varying(255) NOT NULL,
    quantidade_produto integer NOT NULL,
    status character varying(255),
    empresa_id integer,
    CONSTRAINT tbpedido_status_check CHECK (((status)::text = ANY ((ARRAY['AGUARDANDO'::character varying, 'PREPARANDO'::character varying, 'PRONTO'::character varying])::text[])))
);


--
-- Name: tbpedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbpedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbpedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbproduto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbproduto (
    id integer NOT NULL,
    custo double precision,
    descricao character varying(255),
    dt_alteracao timestamp(6) without time zone,
    fl_ativo boolean,
    natureza character varying(255),
    nome character varying(255) NOT NULL,
    preco double precision NOT NULL,
    categoria_id integer,
    empresa_id integer,
    CONSTRAINT tbproduto_natureza_check CHECK (((natureza)::text = ANY ((ARRAY['INSUMO'::character varying, 'REVENDA'::character varying, 'PREPARADO'::character varying])::text[])))
);


--
-- Name: tbproduto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbproduto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbproduto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbsegmento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbsegmento (
    id integer NOT NULL,
    descricao character varying(255),
    fl_ativo boolean,
    nome character varying(255) NOT NULL
);


--
-- Name: tbsegmento_funcionalidade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbsegmento_funcionalidade (
    segmento_id integer NOT NULL,
    funcionalidade character varying(255),
    CONSTRAINT tbsegmento_funcionalidade_funcionalidade_check CHECK (((funcionalidade)::text = ANY ((ARRAY['OPERACAO'::character varying, 'PEDIDO'::character varying, 'COZINHA'::character varying, 'DELIVERY'::character varying, 'ESTOQUE'::character varying, 'COMPRAS'::character varying, 'FINANCEIRO'::character varying, 'PRODUTOS'::character varying, 'CLIENTES'::character varying, 'USUARIOS'::character varying, 'CONFIGURACOES'::character varying, 'CAIXA'::character varying, 'CUPONS'::character varying])::text[])))
);


--
-- Name: tbsegmento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbsegmento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbsegmento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbusuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbusuario (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    fl_ativo boolean,
    fl_sistema boolean,
    nome character varying(255) NOT NULL,
    role character varying(255),
    senha character varying(255),
    empresa_id integer,
    CONSTRAINT tbusuario_role_check CHECK (((role)::text = ANY ((ARRAY['SUPERADMIN'::character varying, 'ADMINISTRADOR'::character varying, 'OPERADOR'::character varying, 'GARCOM'::character varying, 'COZINHEIRO'::character varying])::text[])))
);


--
-- Name: tbusuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbusuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbusuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbvenda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tbvenda (
    id integer NOT NULL,
    desconto double precision,
    dt_alteracao character varying(255),
    dt_criacao character varying(255),
    dt_fechamento character varying(255),
    nome_cliente character varying(255),
    origem character varying(255),
    status character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    valor_total double precision,
    comanda_id integer,
    empresa_id integer,
    mesa_id integer,
    usuario_id integer NOT NULL
);


--
-- Name: tbvenda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tbvenda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbvenda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbadicional tbadicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbadicional
    ADD CONSTRAINT tbadicional_pkey PRIMARY KEY (id);


--
-- Name: tbcaixa tbcaixa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcaixa
    ADD CONSTRAINT tbcaixa_pkey PRIMARY KEY (id);


--
-- Name: tbcardapio tbcardapio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcardapio
    ADD CONSTRAINT tbcardapio_pkey PRIMARY KEY (id);


--
-- Name: tbcashback_config tbcashback_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcashback_config
    ADD CONSTRAINT tbcashback_config_pkey PRIMARY KEY (id);


--
-- Name: tbcategoria tbcategoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcategoria
    ADD CONSTRAINT tbcategoria_pkey PRIMARY KEY (id);


--
-- Name: tbcliente tbcliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcliente
    ADD CONSTRAINT tbcliente_pkey PRIMARY KEY (id);


--
-- Name: tbcomanda tbcomanda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomanda
    ADD CONSTRAINT tbcomanda_pkey PRIMARY KEY (id);


--
-- Name: tbcomposicaoitem tbcomposicaoitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomposicaoitem
    ADD CONSTRAINT tbcomposicaoitem_pkey PRIMARY KEY (id);


--
-- Name: tbcupom tbcupom_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcupom
    ADD CONSTRAINT tbcupom_pkey PRIMARY KEY (id);


--
-- Name: tbempresa tbempresa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbempresa
    ADD CONSTRAINT tbempresa_pkey PRIMARY KEY (id);


--
-- Name: tbendereco tbendereco_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbendereco
    ADD CONSTRAINT tbendereco_pkey PRIMARY KEY (id);


--
-- Name: tbestoque tbestoque_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbestoque
    ADD CONSTRAINT tbestoque_pkey PRIMARY KEY (id);


--
-- Name: tbfornecedor tbfornecedor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbfornecedor
    ADD CONSTRAINT tbfornecedor_pkey PRIMARY KEY (id);


--
-- Name: tbitemcardapio tbitemcardapio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemcardapio
    ADD CONSTRAINT tbitemcardapio_pkey PRIMARY KEY (id);


--
-- Name: tbitemvenda tbitemvenda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvenda
    ADD CONSTRAINT tbitemvenda_pkey PRIMARY KEY (id);


--
-- Name: tbitemvendaadicional tbitemvendaadicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendaadicional
    ADD CONSTRAINT tbitemvendaadicional_pkey PRIMARY KEY (id);


--
-- Name: tbitemvendacomposicaoremovida tbitemvendacomposicaoremovida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendacomposicaoremovida
    ADD CONSTRAINT tbitemvendacomposicaoremovida_pkey PRIMARY KEY (id);


--
-- Name: tbmesa tbmesa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbmesa
    ADD CONSTRAINT tbmesa_pkey PRIMARY KEY (id);


--
-- Name: tbmovimentacao_financeira tbmovimentacao_financeira_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbmovimentacao_financeira
    ADD CONSTRAINT tbmovimentacao_financeira_pkey PRIMARY KEY (id);


--
-- Name: tbpagamento tbpagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpagamento
    ADD CONSTRAINT tbpagamento_pkey PRIMARY KEY (id);


--
-- Name: tbpedido tbpedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpedido
    ADD CONSTRAINT tbpedido_pkey PRIMARY KEY (id);


--
-- Name: tbproduto tbproduto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbproduto
    ADD CONSTRAINT tbproduto_pkey PRIMARY KEY (id);


--
-- Name: tbsegmento tbsegmento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbsegmento
    ADD CONSTRAINT tbsegmento_pkey PRIMARY KEY (id);


--
-- Name: tbusuario tbusuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbusuario
    ADD CONSTRAINT tbusuario_pkey PRIMARY KEY (id);


--
-- Name: tbvenda tbvenda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbvenda
    ADD CONSTRAINT tbvenda_pkey PRIMARY KEY (id);


--
-- Name: tbcomanda ukb9kxfdh1p5b3j75wy0peooq5u; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomanda
    ADD CONSTRAINT ukb9kxfdh1p5b3j75wy0peooq5u UNIQUE (empresa_id, numero);


--
-- Name: tbcupom ukogx7bpjkfbipjbicjsvij6kyy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcupom
    ADD CONSTRAINT ukogx7bpjkfbipjbicjsvij6kyy UNIQUE (empresa_id, codigo);


--
-- Name: tbitemcardapio ukq4nnmau1n7ay20l1w00f27tfm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemcardapio
    ADD CONSTRAINT ukq4nnmau1n7ay20l1w00f27tfm UNIQUE (cardapio_id, produto_id);


--
-- Name: tbcategoria fk19j2m354ctfavw1k6evs9sro3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcategoria
    ADD CONSTRAINT fk19j2m354ctfavw1k6evs9sro3 FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbcomanda fk26apb7jhbw9nnti99kjufjgwq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomanda
    ADD CONSTRAINT fk26apb7jhbw9nnti99kjufjgwq FOREIGN KEY (mesa_id) REFERENCES public.tbmesa(id);


--
-- Name: tbvenda fk2uuouxup4fp4l42mh5162jifl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbvenda
    ADD CONSTRAINT fk2uuouxup4fp4l42mh5162jifl FOREIGN KEY (usuario_id) REFERENCES public.tbusuario(id);


--
-- Name: tbpagamento fk38wmfc71nt6llf85iiolyv8ki; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpagamento
    ADD CONSTRAINT fk38wmfc71nt6llf85iiolyv8ki FOREIGN KEY (venda_id) REFERENCES public.tbvenda(id);


--
-- Name: tbcliente fk3jbv5l001pa3xtsaqiqsswx9h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcliente
    ADD CONSTRAINT fk3jbv5l001pa3xtsaqiqsswx9h FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbitemvenda fk57vl8ymbu174jq6x8djmih1jo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvenda
    ADD CONSTRAINT fk57vl8ymbu174jq6x8djmih1jo FOREIGN KEY (venda_id) REFERENCES public.tbvenda(id);


--
-- Name: tbcupom fk5asqc5bqvxruqpn8k9cygm7f9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcupom
    ADD CONSTRAINT fk5asqc5bqvxruqpn8k9cygm7f9 FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbcomanda fk5e93jk78xpj2x55k9rbkgocer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomanda
    ADD CONSTRAINT fk5e93jk78xpj2x55k9rbkgocer FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbitemvendacomposicaoremovida fk61y1rc7notyfc217occwtp5q3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendacomposicaoremovida
    ADD CONSTRAINT fk61y1rc7notyfc217occwtp5q3 FOREIGN KEY (item_venda_id) REFERENCES public.tbitemvenda(id);


--
-- Name: tbproduto fk66iyr9p6b1abv29y4fc998ubs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbproduto
    ADD CONSTRAINT fk66iyr9p6b1abv29y4fc998ubs FOREIGN KEY (categoria_id) REFERENCES public.tbcategoria(id);


--
-- Name: tbitemcardapio fk6q4h814axlegdgcia1kqu65dd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemcardapio
    ADD CONSTRAINT fk6q4h814axlegdgcia1kqu65dd FOREIGN KEY (cardapio_id) REFERENCES public.tbcardapio(id);


--
-- Name: tbmovimentacao_financeira fk6rlvco2sqdi636wj8inoiavb7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbmovimentacao_financeira
    ADD CONSTRAINT fk6rlvco2sqdi636wj8inoiavb7 FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbvenda fk7qam0aw2f6eg2reu8otarn3c9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbvenda
    ADD CONSTRAINT fk7qam0aw2f6eg2reu8otarn3c9 FOREIGN KEY (comanda_id) REFERENCES public.tbcomanda(id);


--
-- Name: tbcaixa fk9n8419gssy3d0nh9g0vv12qgo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcaixa
    ADD CONSTRAINT fk9n8419gssy3d0nh9g0vv12qgo FOREIGN KEY (usuario_abertura_id) REFERENCES public.tbusuario(id);


--
-- Name: tbestoque fk9xp3jw1pqgc1dvm32w8hhsg3c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbestoque
    ADD CONSTRAINT fk9xp3jw1pqgc1dvm32w8hhsg3c FOREIGN KEY (produto_id) REFERENCES public.tbproduto(id);


--
-- Name: tbvenda fk9ys0q7aa97qkbkgvggmujtisi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbvenda
    ADD CONSTRAINT fk9ys0q7aa97qkbkgvggmujtisi FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbendereco fkadflmbtmariv2vhu7d286iqfn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbendereco
    ADD CONSTRAINT fkadflmbtmariv2vhu7d286iqfn FOREIGN KEY (cliente_id) REFERENCES public.tbcliente(id);


--
-- Name: tbmovimentacao_financeira fkb0m8n0lqe86r1wo583ajympuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbmovimentacao_financeira
    ADD CONSTRAINT fkb0m8n0lqe86r1wo583ajympuy FOREIGN KEY (caixa_id) REFERENCES public.tbcaixa(id);


--
-- Name: tbpagamento fkcacurqrv45p6i9hntc31q5pld; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpagamento
    ADD CONSTRAINT fkcacurqrv45p6i9hntc31q5pld FOREIGN KEY (caixa_id) REFERENCES public.tbcaixa(id);


--
-- Name: tbcashback_config fkeimhj0o2386jq4pjg6ul0hpml; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcashback_config
    ADD CONSTRAINT fkeimhj0o2386jq4pjg6ul0hpml FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbusuario fkernnrjgi2fjfdtrldleb12ke1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbusuario
    ADD CONSTRAINT fkernnrjgi2fjfdtrldleb12ke1 FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbempresa fkfoblwctcgucovi909e9mv0dln; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbempresa
    ADD CONSTRAINT fkfoblwctcgucovi909e9mv0dln FOREIGN KEY (segmento_id) REFERENCES public.tbsegmento(id);


--
-- Name: tbitemvendacomposicaoremovida fkgfd6coyo707qla8y0ihhai8yt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendacomposicaoremovida
    ADD CONSTRAINT fkgfd6coyo707qla8y0ihhai8yt FOREIGN KEY (composicao_item_id) REFERENCES public.tbcomposicaoitem(id);


--
-- Name: tbvenda fkgp9y5vsj2ibsb094dv80o0op5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbvenda
    ADD CONSTRAINT fkgp9y5vsj2ibsb094dv80o0op5 FOREIGN KEY (mesa_id) REFERENCES public.tbmesa(id);


--
-- Name: tbitemvendaadicional fki2rwq37kwqlfre8vnm5sns7cd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendaadicional
    ADD CONSTRAINT fki2rwq37kwqlfre8vnm5sns7cd FOREIGN KEY (adicional_id) REFERENCES public.tbadicional(id);


--
-- Name: tbpedido fkil4i5p1u9mtry7u8i96mwvjk4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpedido
    ADD CONSTRAINT fkil4i5p1u9mtry7u8i96mwvjk4 FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbcardapio fkimd829r6s1nde96rpprmh9o1c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcardapio
    ADD CONSTRAINT fkimd829r6s1nde96rpprmh9o1c FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbfornecedor fkiye67bh8mfc74t9rm8mbacj3e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbfornecedor
    ADD CONSTRAINT fkiye67bh8mfc74t9rm8mbacj3e FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbcaixa fkjqhw19l8s8x2o5vnlqwdeabfx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcaixa
    ADD CONSTRAINT fkjqhw19l8s8x2o5vnlqwdeabfx FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbsegmento_funcionalidade fkk5pdpon8chp74ounmeqoupnid; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbsegmento_funcionalidade
    ADD CONSTRAINT fkk5pdpon8chp74ounmeqoupnid FOREIGN KEY (segmento_id) REFERENCES public.tbsegmento(id);


--
-- Name: tbpagamento fkk8y8h9nl3aqicl6fxfbq8xeko; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbpagamento
    ADD CONSTRAINT fkk8y8h9nl3aqicl6fxfbq8xeko FOREIGN KEY (comanda_id) REFERENCES public.tbcomanda(id);


--
-- Name: tbitemcardapio fkmqw4adoy3h8yycnrwosbht4mn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemcardapio
    ADD CONSTRAINT fkmqw4adoy3h8yycnrwosbht4mn FOREIGN KEY (produto_id) REFERENCES public.tbproduto(id);


--
-- Name: tbitemvendaadicional fkmy1s58a570u518smhujm0lbtv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvendaadicional
    ADD CONSTRAINT fkmy1s58a570u518smhujm0lbtv FOREIGN KEY (item_venda_id) REFERENCES public.tbitemvenda(id);


--
-- Name: tbproduto fkn5vb71eyypuojtg6f17kjv20u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbproduto
    ADD CONSTRAINT fkn5vb71eyypuojtg6f17kjv20u FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbmesa fko28kbsqieu8qxxt098r5avbkk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbmesa
    ADD CONSTRAINT fko28kbsqieu8qxxt098r5avbkk FOREIGN KEY (empresa_id) REFERENCES public.tbempresa(id);


--
-- Name: tbadicional fkp1g94aoxv2pgj8fua2j0jameg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbadicional
    ADD CONSTRAINT fkp1g94aoxv2pgj8fua2j0jameg FOREIGN KEY (produto_id) REFERENCES public.tbproduto(id);


--
-- Name: tbcomposicaoitem fkpue8v8k5l342gcbd365ll9o9a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomposicaoitem
    ADD CONSTRAINT fkpue8v8k5l342gcbd365ll9o9a FOREIGN KEY (produto_id) REFERENCES public.tbproduto(id);


--
-- Name: tbcaixa fkqg58xc0q1ycfsa57ytk134j4l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcaixa
    ADD CONSTRAINT fkqg58xc0q1ycfsa57ytk134j4l FOREIGN KEY (usuario_fechamento_id) REFERENCES public.tbusuario(id);


--
-- Name: tbcomanda fkrrvk7f7i37koctlpq9hms8iim; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbcomanda
    ADD CONSTRAINT fkrrvk7f7i37koctlpq9hms8iim FOREIGN KEY (usuario_abertura_id) REFERENCES public.tbusuario(id);


--
-- Name: tbitemvenda fktdelwlp44yh2qd4f74sb9w28d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tbitemvenda
    ADD CONSTRAINT fktdelwlp44yh2qd4f74sb9w28d FOREIGN KEY (produto_id) REFERENCES public.tbproduto(id);


--
-- PostgreSQL database dump complete
--


