-- Histórico de entrada/saída de estoque. Antes só existia o saldo atual
-- (tbestoque.quantidade_atual); não havia como saber quando ou por que ele
-- mudou. Cada linha aqui corresponde a um ajuste já refletido no saldo —
-- ver EstoqueService.registrarMovimentacao.
CREATE TABLE tbmovimentacao_estoque (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id integer NOT NULL REFERENCES tbproduto (id),
    tipo character varying(20) NOT NULL,
    quantidade integer NOT NULL,
    observacao character varying(255),
    dt_movimentacao timestamp(6) without time zone,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE INDEX idx_movimentacao_estoque_empresa_id ON tbmovimentacao_estoque (empresa_id);
CREATE INDEX idx_movimentacao_estoque_produto_id ON tbmovimentacao_estoque (produto_id);
