CREATE TABLE tbdespesa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao character varying(255) NOT NULL,
    categoria character varying(100) NOT NULL,
    valor numeric(19, 2) NOT NULL,
    dt_despesa date NOT NULL,
    empresa_id integer REFERENCES tbempresa (id)
);

CREATE INDEX idx_despesa_empresa_id ON tbdespesa (empresa_id);
